on:
  push:
    branches: 
      - "unstable"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: ðŸ”– Create System Tags Unstable
jobs:
  build:
    name: ðŸ”– Bump tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create tag
      uses: kangketikonlen/base-tagging@v1.4
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_TYPE: ${{ github.event.repository.owner.type }}
        REPO_OWNER: ${{ github.event.repository.owner.name }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PRESERVE_VERSION: 1